name: Build and Release APK

on:
  push:
    branches:
      - release

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.26.0-0.1.pre
          channel: any

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  create_release:
    name: Create GitHub Release
    needs: build_apk
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: app-release.apk

      - name: Create Release Tag
        id: create_tag
        run: |
          TAG_NAME="v1.0.0"  
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV 
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
